wso2/transport-http

- components/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/contractimpl/HttpResponseStatus.java
- components/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/contractimpl/HttpResponseStatusFuture.java
> Make HttpResponseStatusFuture sync method returns the future itself and add a seperate getter to get the status of the future.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
>N/A
>N/A
>N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Refactor HttpResponseStatusFuture sync method

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/HTTPTransportContextHolder.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/HTTPTransportServiceComponent.java
- pom.xml
Resolves #9 
Current transport version have carbon-messaging dependency for 2.3.7 version which is referring to carbon kernel milestone 3. And we have latest carbon-messaging version 3.0.2 which is referring to latest kernel GA version(5.2.0).
Update carbon-messaging version from 2.3.7 -> 3.0.2
Fix related transport code.
Upgrade carbon-messaging version to 3.0.2
This is just updating the carbon-messaging version. no code level changes.
> Update messaging version to 3.0.2 in transport-http

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpClientConnectorImpl.java
> Currently, the Connection:Close header is not set when sending a request using the client connector while keep-alive is diabled. This will fix this issue by setting the Connection:Close header if keep-alive is enabled. 
> JDK 1.8.0_121
Ubuntu Gnome 16.04
tools: cURL, Chrome 60.0.3112.78
> Set the connection:close header when keep-alive is disabled

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpResponseListener.java
> PR removes the content-type header from the response if the payload is empty. 
> PR adds content length zero headers for the POST, PUT, DELETE, PATCH requests which contain an empty body. 
> PR fixes https://github.com/ballerinalang/ballerina/issues/4022
> To maintain consistent the response headers. Since the content type represents the payload of the response, empty payloads should not have content-type headers. So PR manages to remove it when the content-length header value is zero and content-length header do not exist.
> Remove content-Type for empty payloads and add content length zero

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpClientConnectorImpl.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutBoundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/pool/ConnectionManager.java
> Removing DataSource implementations from the transport implementation. 
DataSource was inherited by the carbon-messaging repository. Now that we are going away from it we need to remove its implementations as well. This is part of that effort.
> Remove the dependency from carbon-messaging implementation. 
> Move DataSource to thin layer of each product.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Covered by existing ones.
- N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Remove DataSource From transport implementation

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/ServerConnectorBootstrap.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/HttpServer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/HttpsServer.java
Resolves #15 
This is to fix unknown channel option warning when server startup. This is because SO_KEEPALIVE and SO_SNDBUF are not channel options for ServerSocketChannels. According to the java docs[1], ServerSocketChannel below options,
Option Name | Description
-- | --
SO_RCVBUF | The size of the socket receive buffer
SO_REUSEADDR | Re-use address
So we need to remove setting those channel options in server bootstrap.
Remove setting  SO_KEEPALIVE, SO_SNDBUF in in server bootstrap.
N/A
N/A
N/A
N/A
N/A, This is a bug fix.
N/A
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
- Ran FindSecurityBugs plugin and verified …
> Fix unknown channel option warning in server startup

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpClientConnectorImpl.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/BlockingEntityCollector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/EntityCollector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java
> Finally, we were able to completed the subject. If you think of separation of concerns DataSource implementations are not really part of the transport but instead a part of the respective products that uses the transport. 
Hence, we have removed it from the transport.
> Make the code more readable and manageable.
> Moving the implementation to respective products.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Covered by existing ones.
- N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Remove all the data-source related code from transport

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/ConfigurationBuilder.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/ListenerConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/RequestSizeValidationConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/SenderConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/TransportProperty.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/TransportsConfiguration.java
This PR is to add default values to fields instead of defining in separate static method. If user need to create object with default values, he can simply create an object of the class.
Remove default method usage when create object with default values.
Add default values to field variables.
depreciate default static method.
> Add default values to field variables instead of defining in default method

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpClientConnectorImpl.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannelListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/CipherSuitesTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/HTTPSClientTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/MutualSSLTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/SSLProtocolsTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassThroughHttpTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/pkcs/PKCSTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/proxyserver/ProxyServerTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestUtil.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/HttpsServer.java
- components/org.wso2.transport.http.netty/src/test/resources/simple-test-config/netty-transports.yml
> There was an issue identified while removing DataSource. It is been fixed with this PR. Basically, when we check the condition for transfer-encoding we also check for the message payload. This logic had some issues when it comes to multi threading. 
> Improve the code to handle multi-threading scenarios. 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Covered by existing ones.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Fix transfer-encoding and test resource issue

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/BlockingEntityCollector.java
> Currently, the message future is not removed from the response message after sending the response. Also, when releasing the entities, the `expectingEntity` property was placed in the wrong section in the `waitAndReleaseAllEntities()` method. This caused issues when using the same response message in the 100 continue scenario, with the client not receiving a content length header which in turn resulted in the client hanging.
> * Remove the message future after the response is sent.
> * Set the `isExpectingEntity` property outside of the check to verify whether the message has already been consumed.
> Remove message future after a finishing the writing of a response

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HTTPTraceLoggingHandler.java
> Fix the issue with the call to write() in trace logging handler not being passed the channel promise.
> Pass the channel promise to write()
> Pass the channel promise to write() in trace log handler

- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
Disable WebSocket Passthrough test case until figure out why it hangs frequently. 
> N/A
>  N/A
>  N/A
>  N/A
>  N/A
> N/A
>  N/A
>  N/A
>  N/A
>  N/A
>  N/A
>  N/A
>  N/A
>  N/A
>  N/A
> Temporary disable WebSocketPassThrough Test Case until Intermittent Hanging is Resolved

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
When headers are added to the outgoing message using setAll, if a header string is already present, this is removed and the new value is set. Since some http headers can be in multiple numbers such as Set-Cookie header, this behavior is not optimal.
Stop removal of headers when headers with same key is present.
Iterated through the headers and called add method, which does not remove headers if present.
N/A
N/A
N/A
N/A
N/A
- Unit tests N/A
- Integration tests N/A
- Confirmed that this PR doesn't commit any keys, passwords, tokens, …
> Adding every headers instead of setAll in out going message

- components/org.wso2.transport.http.netty/pom.xml
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/HTTPTransportServiceComponent.java
`Carbon-Component` header in the `pom.xml` file of `org.wso2.transport.http.netty` module cases to generate following WARN log from Carbon Startup Resolver.
```
WARN {org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager} - Adding a RequiredCapabilityListener from bundle(org.wso2.transport.http.netty:6.0.63), but specified startup component is not available, component-name: netty-transports-mgt
```
Fixes https://github.com/wso2/product-sp/issues/331
- Not causing WARN log
- Remove `<carbon.component>` property from `pom.xml` file of `org.wso2.transport.http.netty` module
- Remove `componentName` property from OSGi `@Component` annotation in `HTTPTransportServiceComponent` class
- Unit tests 
N/A
N/A
- Followed secure coding standards in …
> Remove Carbon Component header from pom.xml of org.wso2.transport.http.netty

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/RequestDataHolder.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/pool/ConnectionManager.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/ClientConnectorConnectionRefusedTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/ClientConnectorTimeoutTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/contentaware/listeners/RequestResponseCreationListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/CipherSuitesTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/HTTPSClientTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/MutualSSLTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/SSLProtocolsTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/pkcs/PKCSTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/proxyserver/ProxyServerTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestUtil.java
> Current code blocks when we calculate the content-length of a given request. This mandates us to use two threads in order to get it working. With this PR I have removed the blocking operation such that the calculation happens in async way. 
In addition to that I have done some refactoring of the code as well. 
> Remove unnecessary thread pools from http transport. 
> Using reactive style of coding.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Covered by the existing ones.
- N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Remove blocking calculation of Content-Length

- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/ClientConnectorConnectionRefusedTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/ClientConnectorTimeoutTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/chunkdisable/ChunkHeaderClientTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/connectionpool/ConnectionPoolTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/contentaware/ContentAwareMessageProcessorTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/contentaware/listeners/RequestResponseCreationListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/contentaware/listeners/RequestResponseCreationStreamingListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/contentaware/listeners/RequestResponseTransformListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/contentaware/listeners/RequestResponseTransformStreamingListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/encoding/ContentEncodingTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/HTTPSClientTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassThroughHttpTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassthroughMessageProcessorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestUtil.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/websocket/WebSocketTestClient.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/HttpServer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/HttpsServer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/SendChannelIDServerInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWsProtocolSwitchTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketClientTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketMessagePropertiesTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketPassThroughTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketPassthroughServerConnectorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketServerTestCase.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
> At the moment we  don't have a test-case to validate the connection re-use of connection pool when we are using the transport for proxy scenarios. This test-case validates it.
In addition to that I have refactored the constant names that are used in Test-Cases.  
> Validate the connection re-use functionality. 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Available
- N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Add testcase for connection re-use in connection-pool

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/ServerConnectorFuture.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/WebSocketInitMessageImpl.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/CustomHttpRequestDecoder.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/EntityCollector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/contentaware/listeners/EchoMessageListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/contentaware/listeners/ResponseStreamingWithoutBufferingListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/redirect/HTTPClientRedirectTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/ChunkBasedServerInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/EchoServerInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/MockServerInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/RedirectServerInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/SendChannelIDServerInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWsProtocolSwitchHttpListener.java
- pom.xml
> To update the Netty version and to remove any usage of the deprecated APIs in Netty.
> Update the Netty version
> Remove usage of deprecated Netty APIs
> Updated the Netty version in the pom
> Added the compiler argument `-Xlint:deprecation` to the maven compiler plug-in in the pom
> Ran a build and fixed each of the warnings given for deprecated API usage by replacing the deprecated versions with their replacement APIs.
> Update Netty version and refactor deprecated Netty API usage

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpWsConnectorFactoryImpl.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/ServerBootstrapConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPConnectorUtil.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HTTPClientInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/BootstrapConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/pool/ConnectionManager.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/pool/PoolConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/pool/PoolableTargetChannelFactory.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/connectionpool/ConnectionPoolEvictionTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/connectionpool/ConnectionPoolMainTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/connectionpool/ConnectionPoolProxyTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/connectionpool/ConnectionPoolTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/CipherSuitesTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/MutualSSLTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/SSLProtocolsTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/pkcs/PKCSTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/proxyserver/ProxyServerTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/redirect/HTTPClientRedirectTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestNGListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestUtil.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/SendChannelIDServerInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWsProtocolSwitchTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketMessagePropertiesTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketPassThroughTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketServerTestCase.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
> While writing a test-cases I realized that making ConnectionManager singleton is wrong. Ideally, it should be per client connector. In addition to that, having singletons turn out to be a bad practice. 
> Hence, I thought of making ConnectionManager per client-connector. While doing so I came across few other singletons which I have removed with this PR.
> In addition to that, When the client connector is used without any association with the server connector, connection pool is not reusing the connections. This has been fixed with this PR as well.
> Improving connection pool implementation.
> Re-using the global connection pool to fix the bug and removing singleton to make the code clean.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Added
- N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Remove singleton ConnectionManager and add testcases

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectHandler.java
> Purpose is to fix the logger error getting printed twice in case an exception is thrown from RedirectHandler
> Separate netty exception handling logic from error handling done for the program code. 
> A common error handling logic is moved to a separate method.
> Fix the logger error getting printed twice when handling redirect exceptions

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/ssl/SSLConfig.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/ssl/SSLHandlerFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/ListenerConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/SenderConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpClientConnectorImpl.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpWsConnectorFactoryImpl.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/ServerConnectorBootstrap.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/HTTP2SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/pool/PoolableTargetChannelFactory.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/pkcs/PKCSTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketServerTestCase.java
> Refactor the APIs of `SenderConfiguration` and `ListenerConfiguration`
> To fix the formatting issues in the APIs of `SenderConfiguration` and `ListenerConfiguration`
> Temporarily disable a problematic test case
> Refactored the APIs with improper capitalizations
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
New tests not needed since it's just an API refactor
- Ran FindSecurityBugs plugin and verified report? no
> N/A
> N/A
> N/A
> N/A
> N/A
> Refactor SenderConfiguration and ListenerConfiguration APIs

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/unitfunction/CommonUtilTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/unitfunction/HttpCarbonMessageTestCase.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
> Validate duplicate header keys existence in transport carbon message
> If a user adds same header key multiple times with different header values, those should not be neglected. 
> Add headers to Http request/response rather than replacing same header key with different values. Most of the times, old headers have been replaced by the new headers of the same key. 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> Adding using this PR
> N/A
N/A
> N/A
> #41 
> N/A
> Java jdk 1.8.0_45 , Linux 16.04
> N/A
> Add unit test cases to validate duplicate header key insertion

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/SenderConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpClientConnectorImpl.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/ClientConnectorClosureAfterRequestReadTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/chunkdisable/ChunkClientTemplate.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/contentaware/listeners/EchoStreamingMessageListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http1point0test/ChunkAlwaysHttpOnePointZeroClientTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http1point0test/ChunkAutoHttpOnePointZeroClientTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http1point0test/HttpOnePointZeroServerConnectorTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http1point0test/KeepAliveHttpOnePointZeroClientTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/unitfunction/CommonUtilTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/http/HttpClient.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/http/ResponseHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/BadEchoServerInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWsProtocolSwitchTestCase.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
> There are can be many legacy clients which still depends on http 1.0 protocol. Hence, this PR provides support for such clients. 
> Supporting http 1.0 clients 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests are added
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Add support for handling HTTP 1.0 messages 

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/CustomHttpContentCompressor.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketServerHandshakeHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HTTPClientInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/compression/ClientRespDecompressionTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/compression/ServerRespCompressionTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/contentaware/listeners/ResponseStreamingWithoutBufferingListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/HTTPSClientTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/HTTPConnectorListener.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
> HTTP transport can send compressed responses and also provides a way to negotiate compressing responses using request header. With transport we provide that support.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- New test-cases are added. 
- No
> N/A
> N/A
> N/A
> N/A
> N/A
> Add support for handling compressing request and decompressing response

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
> Related issue: https://github.com/ballerina-lang/ballerina/issues/4706
> Setting of this header would be done in ballerina. This allows more flexibility.
>JDK 8 | Ubuntu 17.10
> Remove Accept-Encoding header in outbound request

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/headers/DateHeaderTestCase.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
> Currently, the `Date` header is not set if the user has not set it. The correct behaviour should be such that if the user hasn't set the header, it should be set. Fix [ballerina/issues/4641](https://github.com/ballerina-lang/ballerina/issues/4641)
> Set the `Date` header in accordance with the HTTP specification.
> [Date - HTTP specification](https://tools.ietf.org/html/rfc7231#section-7.1.1.2)
> Check if the outbound response contains the `Date` header field and if it's absent, set the date, using the RFC1123 date formatter provided in JDK.
> Set the Date header in accordance with the HTTP spec

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/KeepAliveConfig.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/ListenerConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HttpServerChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/ServerConnectorBootstrap.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/HTTPProtocolNegotiationHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http1point0test/HttpOnePointKeepAliveNeverTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http1point0test/HttpOnePointOneKeepAliveDefaultCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/multipartdecoder/MultipartTestCase.java
> Resolve https://github.com/ballerina-lang/ballerina/issues/4806
> Fix the keep-alive configuration not working in the server-connector.
>  Fix by adding it to the Listener configuration
- Unit tests 
> Added in transport-http
> https://github.com/ballerina-lang/ballerina/pull/4835
> Fix keep-alive config not working

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
> Remove content-length header before setting it again. This is useful when you are sending the same request again and again. 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Remove content-length header before setting

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HttpAccessLoggingHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HttpServerChannelInitializer.java
> Related issue: https://github.com/ballerina-lang/ballerina/issues/4444
> Access logs will be printed in the console
> The access logs are supported as per https://httpd.apache.org/docs/current/logs.html#combined
> https://github.com/ballerina-lang/ballerina/pull/4913
> Support standard access logs

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
> Avoid creating eventloop groups for each and every client. But instead create on for each factory.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Use the same eventloop group for client connector

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/ListenerConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HttpServerChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/ServerConnectorBootstrap.java
> Related issue: https://github.com/ballerina-lang/ballerina/issues/4444
>Fix access log being on by default
> Add to listener configuration
> https://github.com/wso2/transport-http/pull/67
> https://github.com/ballerina-lang/ballerina/pull/4913
> Add configuration for access log

- .travis.yml
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/exception/EndpointTimeOutException.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/ClientConnectorTimeoutTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassthroughMessageProcessorListener.java
When an endpoint timeout occurred, the listener will be notified with a client connector exception. this will introduce EndpointTimeoutError which will be helpful to implement programs more resilient to failures.
> Introduce Timeout exception

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/HttpResponseFuture.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpResponseFuture.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/Http2OutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/Http2SourceHandlerBuilder.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2ClientChannel.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/OutboundMsgHolder.java
Need to improve error handling of HTTP/2 related operation.
- Prevent writing a push response to rejected stream
- Prevent trying to fetch a promised response for a rejected promise
- Throw errors which trying to do HTTP/2 related operation on HTTP/1.x server side connections.
Goal is to improve error handling on  HTTP/2 related operation.
Fixes to above mentioned facts are included in this PR.
N/A
N/A
N/A
If sync() operation is need to be called more than once in a single HttpResponseFuture object,
resetStatus() must be …
> Improve error handling related to HTTP/2 operations

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/CustomHttpContentCompressor.java
> Is to fix content-encoding issue which used the original request message's Accept-Encoding value instead of the settings defined by configuration.
> Fix content-encoding issue in custom compressor
> Override  acceptEncoding value in beginEncode() method
> Fix content-encoding issue in custom compressor

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HttpClientChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TLSHandshakeCompletionHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java
Fix the null pointer exception which comes when an error occurs.
When an error occurs, in a TLS handshake it was giving a null pointer error since the target handler was not set at that moment.
As a solution, removed the rest of the handlers(including target handler) from the pipeline after SSLHandler if the handshake fails.
> Fix the null pointer issue in target handler

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/ssl/SSLConfig.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/ssl/SSLHandlerFactory.java
Earlier we didn't have control for ssl session creation. By default it is set to true and user cannot control whether to establish new ssl sessions or to disable creating new ssl sessions.
Allow user to control ssl session creation.
A parameter is introduced to control this (sessionCreationEnabled). By default this will be set to true which is the default way used in Java. 
> List any other related PRs
Related issue : https://github.com/ballerina-lang/ballerina/issues/5345
> Allow user to control ssl session creation

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/CertificateValidationHandler.java
Server/client fails to create the http pipe line after certificate validation is enabled, since it fails to send go to the SSLHandshakeCompletion handler. 
Fire the user event inside the certificate validation handler.
> Fix the issue of not creating http pipeline when certificate validatiion is enabled

- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassThroughHttpsTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassthroughHttpsMessageProcessorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassthroughMessageProcessorListener.java
Add source handler in both http and https pass-through test cases.
Remove setting keystore as a system property since it is not required.
> Add source handler in pass-through test cases

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/websocket/WebSocketAsyncRemoteEndpoint.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/websocket/WebSocketSessionImpl.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketClientTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketPassthroughClientConnectorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketPassthroughServerConnectorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketTestClientConnectorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketTestServerConnectorListener.java
> Use async RemoteEndpoint for WebSocket
Related issue https://github.com/ballerina-lang/ballerina/issues/6069
> Make WebSocketEndpoint to implement the RemoteEndpoint.Async interface and hence WebSocketSessionImpl would now implement the method getAsyncRemote().
> Use async RemoteEndpoint for WebSocket

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/BlockingEntityCollector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/EntityCollector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
> At the moment we only have a method get the complete message length. But we do so it required to keep the entire payload in memory till we complete the count. 
But with this method we only count till the maximum message length. As soon as it is reached, this method returns with the counted value.
I have created two new issues as improvements. 
[1] https://github.com/ballerina-platform/ballerina-lang/issues/6933
[2] https://github.com/ballerina-platform/ballerina-lang/issues/6930
> Add a method to count message length

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/ssl/SSLHandlerFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HttpClientChannelInitializer.java
Earlier we passed sslEngine from the PoolableTargetChannelFactory. Now we will not pass it from there, but create the sslEngine directly inside the httpClientChannelInitializer using sslConfig.
> Refactor httpClientChannelInitializer

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/Http2SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/ClientInboundHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/ClientOutboundHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2ClientChannel.java
Requests get hanged in the middle of a load test due to concurrency issues related to stream creation in HTTP/2. Need to address those issues.
Fix request hanging issues found with a load test.
- Fix synchronization issues with stream creation.
- Improve debug logs to ease debugging
N/A
N/A
JDK 1.8
> [HTTP2] Fix request hanging issues found with a load test

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/websocket/WebSocketBasicRemoteEndpoint.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/websocket/WebSocketSessionImpl.java
> Add synchronized message sending support in WebSocket
> Implement basic remote endpoint of javax.websocket interface
> Tests are not included and added an issue to track it -> https://github.com/wso2/transport-http/issues/107 
> Add implementation of WebSocket Basic Remote Endpoint

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/SenderConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/pool/PoolConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2ConnectionManager.java
Http2MaxActiveStreams parameter currently defined in the SenderConfiguration.But it is a parameter belongs to http2 connection pool, so it need to be placed on the PoolConfig.
Move Http2MaxActiveStreams parameter to PoolConfig.
> Move Http2MaxActiveStreams parameter to PoolConfig

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/SenderConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HttpClientChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http1point0test/KeepAliveHttpOnePointZeroClientTestCase.java
This will introduce enum for keep-alive configuration in sender configuration.
> Use Enum for Keep-Alive Config in Sender

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpResponseFuture.java
>  Remove listener once it is notified. This was required as the listener is set to the listener during every action
> Remove listener after notifyHttpListener

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HttpClientChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectUtil.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/ClientInboundHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/ClientOutboundHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2DataEventListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/OutboundMsgHolder.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/RedirectHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/TimeoutHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ClientConnectorBasicTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ClientTimeoutTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2RedirectionTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ServerConnectorBasicTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ServerPushTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2WithPriorKnowledgeTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/listeners/Http2RedirectListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/listeners/Http2ServerConnectorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/redirect/HttpClientRedirectTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/http2/MessageGenerator.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
Redirection is not working for HTTP/2 with the existing RedirectionHandler. So need to introduce redirection functionality to HTTP/2
Add Redirection support for HTTP/2 
Added a new Http2DataEventListener to handle HTTP/2 redirection.
- Unit tests 
Included in the PR.
JDK 1.8
> Add Redirection support for HTTP/2 

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketInitMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/Http2SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/MaxEntityBodyValidator.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/ServerConnectorBootstrap.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketServerHandshakeHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketSourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/DefaultListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/DefaultObservable.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonRequest.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonResponse.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/Listener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/Observable.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/ClientInboundHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/forwardedextension/ForwardedClientTemplate.java
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/7291
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/7371
> Set a threshold of MAXIMUM_BYTE_SIZE = 2MB when reading the content to the carbon message.
> Prevent OOM error occurs due to unlimited reading
> Observe carbon message content add/remove through a listener and pause channel read when the upper limit is reached.
> Throttle READ for inbound entity body

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/redirect/HttpClientRedirectTestCase.java
Retrieve the ultimate url of the server, from which the response came from and include it in the response.
A new property called "resolvedRequestedURI"  is included as a field to the HTTP response object.
> Contains an integration test.
Fixes : https://github.com/ballerina-platform/ballerina-lang/issues/7346
> Include ultimate request url in the response when redirect is on

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
Currently when a SslCloseCompletionEvent event triggers, it is shown to the user as a warning message. Since this is confusing to the user we should avoid notifying them as warning messages.
> Handle sslCompletionEvent from Target handler and Source handler

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/Http2OutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/Http2SourceHandler.java
Since reject promise resets a given steam, if the server tries to write to a already rejected stream, there is a chance of server failed to write and send a GO_AWAY frame which will endup in a connection failure. Need to fix that issue.
Fix intermittent connection close issue related to reject promise.
> Fix intermittent connection close issue related to reject promise

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
> During the pass-through case, getContent is called at first. PR fixed the hanging issue by calling adding content first.
> Fix pass-through hanging issue due to auto read false

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketConnection.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketInitMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketConnection.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/WebSocketInboundFrameHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketInitMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/WebSocketCloseMessageImpl.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/websocket/WebSocketUtil.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketServerHandshakeHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketSourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketTargetHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWebSocketProtocolSwitchTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWsProtocolSwitchWebSocketListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketPassthroughServerConnectorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketTestServerConnectorListener.java
> To fix the protocol violation addressed by issue https://github.com/ballerina-platform/ballerina-lang/issues/7893
> Resolve the WebSocket protocol violation when closing the connection
> Change the implementation of WebSocketConnection to match the protocol connection closing description.
- Unit tests 
> No
> Added an issue https://github.com/wso2/transport-http/issues/115 to address this separately since this needs different test clients to test different scenarios.
> No
> [WebSocket] Fix protocol violation of connection closure

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketInitMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketInitMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketServerHandshakeHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWsProtocolSwitchWebSocketListener.java
> This adds more changes to the cancelling handshake method:
- Restricts the status error status codes
- Returns a channel future
Further the makes sure that the `WebSocketInitMessage` returns the proper `HttpCarbonRequest` instead of the `HttpRequest`.
> Fix incorrect cancelling of the handshake

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
Added a comment to understand why we ignored ChannelInputShutdownReadComplete event.
> Add a comment for ignoring the ChannelInputShutdownReadComplete event

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/ClientOutboundHandler.java
> At the moment, we manually have to remove the aforementioned future upon completed the life-cycle of the message. With this PR we do that automatically.
> Remove message future automatically 

- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/chunkdisable/ChunkAutoServerTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/chunkdisable/ChunkDisableServerTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/chunkdisable/ChunkEnableServerTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/headers/Continue100TestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/http/FullHttpResponseMessage.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/http/HttpClient.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/http/ResponseHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWebSocketProtocolSwitchMultiThreadTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWebSocketProtocolSwitchTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketMessagePropertiesTestCase.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
Refactoring Httpclient implementation to handle chunking. 
Fix chunking related test cases in a proper manner.
Remove HttpObjectAggregator netty handler used in Httpclient and alter the ResponseHandler implementation to handle chunking behavior correctly.
- Unit tests 
> yes
> Refactor transport test cases

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketConnection.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketConnection.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/WebSocketInboundFrameHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketClientFunctionalityTestCase.java
> Allow terminating a connection with a close frame
>Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/8145
> This helps to close a connection by sending a close frame but need not wait for a close frame.
> Adds a method that sends a close frame and terminates the connection without waiting for a response.
> Allow terminating a connection with a close frame

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/ListenerConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HttpServerChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/ServerConnectorBootstrap.java
if the socket timeout value is 0, do not set a default timeout since 0 means "disable timeout".
> Remove default socket timeout value

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SslHandshakeCompletionHandlerForServer.java
Remove the SslHandshakeCompletion handler after configuring the http pipeline.
And then fireChannelActive from the ctx without giving the entire serverPipeline.
> Remove the SslHandshakeCompletion handler after creating pipeline

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceErrorHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
When there is a connection timeout currently the channel is closed. In this PR if the timeout is during the reception of a request or after completion of the reception of the request a response is sent back to inform the client. If it is the timeout when reading the request 408 Request Timeout is sent. If it is the timeout before writing a response a 500 internal server error is sent.
Resolve ballerina-platform/ballerina-lang#3794
> Send back response when timeout

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/method/head/HeadRequestMessageProcessorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/method/head/HeadRequestTestCase.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
> Fix https://github.com/ballerina-platform/ballerina-lang/issues/7619
> Discard entity body correctly and construct response for HEAD request.
> Add necessary parts to discard the entity body and construct response in HttpOutboundResListener
- Unit tests 
> Yes
> No
> Fix response for HEAD method

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/SourceInteractiveState.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceErrorHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
> Add EXPECT_100_CONTINUE_HEADER_RECEIVED and RESPONSE_100_CONTINUE_SENT special states to sourceErrorHandler to indicate states of 100 continue requests.
> Address application layer problem of responding to a request which has not been read completely. In that instance, states are changed from RECEIVING_ENTITY_BODY to SENDING_ENTITY_BODY. Since user doesn't consume the inbound request payload, the connection is closed after checking this state inconsistent transition.
> Add 100-continue specific states

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketHandshaker.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketServerHandshakeHandler.java
> This fixes the `channelInactive` of `SourceHandler` not being called because it is overridden at the `WebSocketServerHandshakeHandler`. Now the channel becoming inactive at the cancelling of handshake would be handled as soon as the canclled response is sent to the client by closing the `ChannelHandlerContext`
Fix https://github.com/ballerina-platform/ballerina-lang/issues/10043
> Fix overriding channelInactive before SourceHandler

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceErrorHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
> When idle timeout was triggered after the entire payload was received, the server did not respond consistently. This fixes this issue.
Resolve https://github.com/ballerina-platform/ballerina-lang/issues/9950
> Fix server idle not responding at times

- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/certificatevalidation/OCSPStaplingTest.java
This test contains getting a response from CA for a particular certificate.
Disabling this test for the moment as it fails in Jenkins.
> Disable an ocsp stapling test

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketConnection.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketConnection.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/WebSocketInboundFrameHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/websocket/WebSocketRemoteServerFrameHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketClientFunctionalityTestCase.java
> Netty returns -1 if statusCode is lacking in close. This PR displays it to the user as 1005 based on WebSocket spec. Also the PR allows for initiating and finishing close without a close status code.
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/10135
> Fix incorrect behavior for lacking statusCode in close

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/Http2SourceConnectionHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/Http2SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/ClientFrameListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2ClientChannel.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/TimeoutHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/CipherSuitesTest.java
- Use LOG as logger variable name
- Fixes ballerina-platform/ballerina-lang#10370
> Unify the logger variable name of HTTP/2 classes

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/HttpServerChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/TargetChannel.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClient.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/WebSocketInboundFrameHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketHandshaker.java
Makes sure connection is closed only for ALL_IDLE event. Earlier the connection was closed for READER_IDLE or WRITER_IDLE events as well.
Resolve https://github.com/ballerina-platform/ballerina-lang/issues/10381
> Fix idle timeout to use only ALL_IDLE

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketHandshaker.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketServerHandshakeFunctionalityTestCase.java
> This would prevent a null pointer when a WebSocket request with an unsupported version is sent.
> Respond properly for unsupported WebSocket version

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/ResponseCompleted.java
> State changing to connected stated once the response is complete is not necessary. It results an extra log printed in the log when the connection is closed.
> Remove unnecessary state change

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketConnectorFuture.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketConnectorListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketConnectorFuture.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/WebSocketInboundFrameHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketTestClientConnectorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/passthrough/WebSocketPassThroughClientConnectorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/passthrough/WebSocketPassThroughServerConnectorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketServerHandshakeFunctionalityListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketTestServerConnectorListener.java
The onClose method for the WebSocketConnectorListener has been introduced in order to let the listener know when the connection closes. This method will be called only after the user is notified of a close message or an error message. Also note that this method will be called only after the futures of connection closure methods return.
Related issue: https://github.com/ballerina-platform/ballerina-lang/issues/10667
> Add onClose method to the ConnectorListener

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/StateUtil.java
This fix for adding multiple last contents at passthrough scenario when the inbound response received while sending the outbound request at passthrough service.
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/10774
> Fix for adding multiple last contents at passthrough scenario

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/EntityBodyReceived.java
> WriteOutboundRequestEntity method of EntityBodyReceived class might get called when inbound response is received but outbound request is not yet completed.In that instance, remote host doesn't require request content anymore, Therefore contents are released using this PR.
> Release not consuming outbound request contents

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/HttpServerChannelInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/TestHttp2WithALPN.java
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/10936
This PR fixes a scenario of HTTP/2 to HTTP/1.1 fallback. The following ballerina program acts as a backend service and it can be invoked by 
`$ curl -k https://localhost:9191/nyseStock/stocks`.
The PR fixes this scenario while removing the NPE occurred at `OutboundRespListener.java` class.
```ballerina
endpoint http:Listener passthroughEP {
port: 9191,
httpVersion: "2.0",
secureSocket: {
keyStore: {
path: "${ballerina.home}/bre/security/ballerinaKeystore.p12",
password: "ballerina"
}
}
};
@http:ServiceConfig { basePath: "/nyseStock" }
service<http:Service> nyseStockQuote bind passthroughEP {
@http:ResourceConfig {
path: "/stocks"
}
stocks(endpoint outboundEP, http:Request clientRequest) {
http:Response res = new;
json …
```
> Fix an HTTP/2 to HTTP/1.1 fallback scenario

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/BackPressureHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/HttpServerChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/WebSocketServerHandshakeHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/HttpClientChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/TargetChannel.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingHeaders.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/BackPressureListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/BackPressureObservable.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/DefaultBackPressureListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/DefaultBackPressureObservable.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/DefaultListener.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/MessageFuture.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/PassthroughBackPressureListener.java
Client can go OOM if the server is slow during a send operation because of data collecting in the netty buffer. Similarly server can go OOM if the client is slow during a respond operation. Outbound throttling fixes this issue.
The following scenarios require outbound throttling and are addressed in this PR:
- Server responding with a large file.
- Client sending a large file to server.
- Passthrough of a large request file.
- Passthrough of a large response file.
> Add outbound throttling

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ReceivingEntityBody.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/SendingEntityBody.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/SendingHeaders.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/EntityBodyReceived.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingEntityBody.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingHeaders.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/RequestCompleted.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SenderState.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SendingEntityBody.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SendingHeaders.java
gRPC bidirectional streaming is falling because we not allow to sent any more data frames for the request, when response is received. But in gRPC bidirectional streaming scenario, caller and server can send and receive any number of data frames in same stream before one of the party close it. 
This PR is to fix bidirectional streaming issues in http2 transport.
> Fix bidirectional streaming issues in http2 transport

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/Expect100ContinueHeaderReceived.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/headers/Continue100TestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/listeners/Continue100Listener.java
> Handle status codes other than 100 at Expect100ContinueHeaderReceived state.
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/12494
>  Handle Expect: 100-continue negative scenario

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketHandshaker.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/WebSocketServerCompressionHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/WebSocketServerHandshakeHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClient.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClientCompressionHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClientHandshakeHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/WebSocketInboundFrameHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketHandshaker.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/websocket/WebSocketTestClient.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketServerHandshakeFunctionalityListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketServerHandshakeFunctionalityTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketTestServerConnectorListener.java
> Resolve spec violations in WebSocket:
> - [server report](http://riyafa.github.io/Riyafa-Abdul-Hameed--web-page/others/reports/servers/)
>This PR resolves as much as possible of the spec violations. Not all spec violations have been resolved because they have not been resolved in netty itself.
>Following are added in this PR:
- Adds compression support for WebSocket Server
- Fixes issue with Reserved Bits usage on the server side
Resolve ballerina-platform/ballerina-lang#12694
- Adds UTF-8 validation check for WebSocket frames.
Resolve ballerina-platform/ballerina-lang#12696
Resolve ballerina-platform/ballerina-lang#12695
- Fixes compression related issues
Related issue: ballerina-platform/ballerina-lang#12698
Related issue: ballerina-platform/ballerina-lang#12702
The compression …
> Resolve spec violations in WebSocket

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/SslConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/ssl/SSLHandlerFactory.java
When you don't specify the verifyClient option, you get a warning message saying 'Received an unidentified configuration for sslVerify client. Hence client verification will be disabled which is the default configuration.'. This is an unnecessary warning message and removed it.
> Remove the warning logs if verifyClient is not set

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/SenderConfiguration.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/forwardedextension/ForwardedDefaultTestCase.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
Transport shouldn't modify Forwarded/X-Forwarded header by default if the user doesn't specifically configure to do so.
- Unit tests 
> Yes
> Set default forwarded configurations to disabled

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java
Initializing Http Carbon Message properties map with default size to avoid resizing of the map to improve the performance
Minimize the possibility of the capacity resizing of the hash map used in HttpCarbonMessage to improve the performance.
> Set proper init value for Carbon Message properties map

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/SslConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/ssl/SSLConfig.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/ssl/SSLHandlerFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/HttpServerChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/HttpClientChannelInitializer.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ALPNwithCertsTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/TestHttp2WithALPN.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/MutualSSLTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/MutualSSLwithCertsTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestUtil.java
Currently, there is no way of changing the default values of SSL session time out and SSL handshake time out. This PR is to introduce the capability to set SSL handshake and session time outs as a user prefers.
Fixed issues: https://github.com/ballerina-platform/ballerina-lang/issues/13847
https://github.com/ballerina-platform/ballerina-lang/issues/13846
> Support setting ssl handshake/session time out

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/SourceHandler.java
$subject. Fixes https://github.com/wso2/transport-http/issues/305
Close connection after SslCloseCompletionEvent
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests - N/A
- Integration tests -  N/A
N/A
N/A
N/A
N/A
N/A
> Fix IDLE_TIMEOUT_TRIGGERED_BEFORE_INITIATING_INBOUND_REQUEST when ssl handshake fails

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/ResponseCompleted.java
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/12815
> Release remnant content of inbound carbon message in the response completed state.
> Release remnant content in inbound HTTPCarbonMsg

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2ClientChannel.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2TargetHandler.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/TestExhaustedStreamIdForClient.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/http2/MessageSender.java
$subject. 
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/14380
> Remove HTTP/2 client connection from the pool when the stream ids are exhausted 

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java
> Clears the Byte Buffer and release remnant HTTP Content
> Avoid possible memory leak if input stream read() function fails to read up to the limit.
> Check whether content release status by refCnt method. Release content only if the count is above 0.
> Clears the buffer
> Override ByteBufferInputStream close() function

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/ReceivingEntityBody.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java
> This PR will add console logs to identify a possible test failure path. This change will be reverted in the next immediate release. 
Please note that do not use 6.0.280 HTTP transport version
> Add logs temporarily  to identify test failure 

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java
> This PR will add stacktrace logs to identify a possible test failure path. This change will be reverted in the next immediate release. 
Please note that do not use 6.0.282 HTTP transport version
> Add stacktrace to data stream close function

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java
> This PR will add stacktrace logs to identify a possible test failure path. This change will be reverted in the next immediate release. 
Please note that do not use 6.0.283 HTTP transport version
> Remove content read

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/TargetChannel.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2Content.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/OutboundMsgHolder.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/RequestWriteStarter.java
$subject is a prerequisite for Http/2 flow controlling for client
> Move HTTP/2 request's content writing logic out of I/O thread

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java
> This PR will add stacktrace logs to identify a possible test failure path. This change will be reverted in the next immediate release. 
Please note that do not use 6.0.286 HTTP transport version
> Remove super close()

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
> Prevent waiting when shutting down the connector factory
> Stop waiting when shutting down a DefaultHttpWsConnectorFactory by avoiding waiting for the future until it is done
> Prevent waiting when shutting down the connector factory

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/expect100continue/Abnormal100ContinueTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/expect100continue/Continue100TestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/Abnormal100ContinueServerInitializer.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
Some HTTP servers could respond with 100 continue before sending the payload even though the request does not have Expect: continue header. This PR is to handle such scenario. 
P.S. - Same fix was done few days ago by Bhashinee. I just improved that fix and added a test-case.
> Handle abnormal 100 continue response

- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
$subject fails intermittently hence disabling them for now.
> Disable HTTP/2 data write tests

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/ListenerConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketClientConnectorConfig.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/HttpServerChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/ServerConnectorBootstrap.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/WebSocketServerHandshakeHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClient.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketClientFunctionalityTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketClientHandshakeFunctionalityTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketServerHandshakeFunctionalityTestCase.java
> Add a parameters to support enabling or disabling the support of compression in WebSocket
> Support  configuring the WebSocket Compression
> Add a new config param to Listener and client configs.
>N/A
> API change to http Listener and WebSocket client config.
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> added
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> N/A
> 
> N/A
> JDK 8
> N/A
> Enable configuring the WebSocket Compression

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/BlockingEntityCollector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/EntityCollector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/unitfunction/BlockingEntityCollectorTestCase.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
> Use same Endpoint timeout interval for the poll action.
> Update countMessageLengthTill function to throw IllegalStateException upon polling timeout expired
> Provide proper error when polling is expired
> Prevent execution hanging issue while polling as it did not had a timeout
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> Provide high-level details about the samples related to this feature
> List any other related PRs
> Describe migration steps and …
> Add IllegalStateException for countMessageLengthTill method

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/SenderReqRespStateManager.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/StateUtil.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SendingEntityBody.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SendingHeaders.java
> SendingEntityBody had some logic related to writing headers. Hence, refactored the code to have proper abstraction.
Also targetChannel was over used. Hence, removed unwanted usage of that too.
> Refactor SendingHeaders and SendingEntityBoby states of sender

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java
> $Subject.
> This is not related to HttpContent.refCnt. We maintain a count privately to release the consumed content
> Avoid memory leaks and do proper content release
> https://github.com/ballerina-platform/ballerina-lang/pull/18305
> Add referenceCount to track content release

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/SslConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/ssl/SSLConfig.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/ssl/SSLHandlerFactory.java
Get the java default context when the user hasn't provided any truststore information.
> Get the java default ssl context

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/SourceHandler.java
Once the peer closes the connection channel  automatically gets closed from both sides. That's the default behavior of netty.
If we want to use half close that has to be configured specifically using 'setAllowHalfClosure' method. 
>> https://netty.io/4.0/api/io/netty/channel/socket/SocketChannelConfig.html#setAllowHalfClosure-boolean-.
But with HTTP protocol that is not necessary.  
Using close on an already closed connection causes RST packets.
> Remove unnecessary connection close

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/HttpClientChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/SslHandshakeCompletionHandlerForClient.java
Fix the issue: https://github.com/ballerina-platform/ballerina-lang/issues/19687
> Skip the certificate expiration date validation when the user has disabled ssl validation

- components/org.wso2.transport.http.netty.statistics/pom.xml
- components/org.wso2.transport.http.netty/pom.xml
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ReceivingHeaders.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/SendingEntityBody.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingHeaders.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SendingEntityBody.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/http2forwardedextension/Http2ForwardedTestUtil.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/listeners/Http2EchoServerWithTrailerHeader.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/trailer/H2ClientRequestTrailerHeaderTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/trailer/H2ListenerIntendedResponseTrailerHeaderTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/trailer/H2ListenerPushResponseTrailerHeaderTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/trailerheader/H2ListenerTrailerHeaderTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/Http2Util.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
- features/org.wso2.transport.http.netty.feature/pom.xml
- features/org.wso2.transport.http.netty.statistics.feature/pom.xml
- pom.xml
> Add API to hold trailing headers in the carbon message.
> Implement user provided trailing header handling process.
> Fix payload hanging issue due to trailing header set
> Add Trailer header internally after http2-to-http header conversion
> Provide API to process trailing headers(https://tools.ietf.org/html/rfc7540)
- Unit tests 
> Added
> N/A
```
HEADERS
- END_STREAM
+ END_HEADERS
:status = 200
content-length = 123
content-type = image/jpeg
**trailer = Foo**
DATA
- END_STREAM
{binary data}
HEADERS
+ END_STREAM
+ END_HEADERS
**foo = bar**
```
> List any other related PRs
> Refactor HTTP2 Trailer header logic and add test cases

- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketClientFunctionalityTestCase.java
- pom.xml
> $Subject
> Fix websocket test failure (Recently Netty has refactored websocket error handling via netty/netty#9116)
> Upgrade Netty version to 4.1.45

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/StateUtil.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingEntityBody.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingHeaders.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/trailer/ClientReadTrailerHeaderTestCase.java
> Prevent having redundant trailers during passthrough case
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/22190
> Clear trailers in the **LastHttpContent** once consuming it from the HttpCarbonMessage. Otherwise same headers will get populated when responding
- Unit tests 
> Added
> N/A
> Clear trailers from LastHttpContent after consuming

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/exceptions/ClientClosedConnectionException.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/SourceHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/EntityBodyReceived.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/EntityBodyReceived.java
This PR introduces a specific exception class called `ClientClosedConnectionException` to throw when the remote client abruptly close the connection.
> Introduce ClientClosedConnectionException class

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/Http2OutboundRespListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/compression/ResponseBodyCompressionTestCase.java
Fix the https://github.com/ballerina-platform/ballerina-lang/issues/24977
Fix the issue of HTTP2 server not encoding when the request is sent with multiple values in `accept-encoding` header.
In HTTP1.1, this is done in [HttpContentCompressor](https://github.com/netty/netty/blob/0992718f87bf0f0c23660489b1f7e697a24f2a4b/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java) by checking the `accept-encoding` header in this [determineWrapper](https://github.com/netty/netty/blob/0992718f87bf0f0c23660489b1f7e697a24f2a4b/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java#L175) function. Same logic is applied in this PR, before setting the `content-encoding` header in the response. 
> An integration test was already there …
> Fix the issue with HTTP2 content-encoding

- pom.xml
> $subject
```
During the OB/MGW analysis, it was found that,
snakeyaml 1.16 is used in ballerina and bundled into the platform.zip in mgw pack.
Both the dependency versions impose the following threat.
CVE-2017-18640:
org.yaml_snakeyaml- 1.16/1.23
CVE-2017-18640
High
The Alias feature in SnakeYAML 1.18 allows entity expansion during a load operation, a related issue to CVE-2003-1564.
Vulnerable Package: org.yaml_snakeyaml
Current Version: 1.16/1.23
Fixed in 1.26
High
CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H (CVSS v3 base score: 7.5)
http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2017-18640
```
> Upgrade orbit/snakeyaml version to 1.26.0.wso2v1

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/InboundMsgSizeValidationConfig.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/ListenerConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/SenderConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/HttpServerChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/ServerConnectorBootstrap.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/UriAndHeaderLengthValidator.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/HttpClientChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/ResponseEntityBodySizeValidator.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/StatusLineAndHeaderLengthValidator.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/TargetHandler.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/RequestCompleted.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/lengthvalidation/RequestLengthValidationTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/lengthvalidation/ResponseLengthValidationTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassthroughMessageProcessorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/urilengthvalidation/Status414And413ResponseTest.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
> Add following configs to the HTTP client
- maxInitialLineLength
- maxHeaderSize
- maxEntityBodySize
- maxChunkSize
> Plug header and entity body validator handlers to the client channel.
> Generalize request and response validation configs logic
> Change request validation error status code form 413 to 431
- Unit tests 
> Added
> Make the inbound response size validation configurable

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingHeaders.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/trailer/H2ListenerTrailersInInitialHeaderFrameTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/trailer/SendHeadersWithoutDataFrameInitializer.java
- components/org.wso2.transport.http.netty/src/test/resources/testng.xml
> $subject
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/27636
> Fix HTTP2 inbound response headers getting mixed up with trailer validation logic

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/SendingEntityBody.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/RequestCompleted.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java
> While streaming events with siddhi-sse, remote client closed connection logs should not be displayed.  
> Remove the unnecessary logs while streaming responses.
> Add streaming property to carbon message

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/ListenerConfiguration.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/SslConfiguration.java
> Add HTTP response headers including strictTransportSecurityHeader
> Configure headers such as HTTP Strict Transport Security, Referrer-Policy, Feature-Policy, Content-Security-Policy, etc in carbon transports.
> Adding the header values configured in netty-transports.yml into the HTTP response.
Users have to configure HSTS header values in netty-transports.yaml under listener configurations as follows.
id: "msf4j-https"
....
scheme: https
....
strictTransportSecurityHeader: max-age=342352535; includeSubDomains
responseHeaderList: "Feature-Policy: microphone 'none'; geolocation 'none', Referrer-Policy: no-referrer"
Multiple headers can be added to responseHeaderList which can be separated by commas (",") . `responseHeaderList` and `strictTransportSecurityHeader` configuration values in …
> Add missing ssl configs and headers in listener

- components/org.wso2.transport.http.netty/pom.xml
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/SslConfiguration.java
> Initialise ssl config with  keyStoreFile and keyStorePassword which was initialised with the yaml loader.
> Private package snakeyaml due to complexities arised when used with msf4j due to different snakeyaml versions used.
> Fix for configuring listener SSL config

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpResponseFuture.java
When the channel is not writable but active, it acquires a semaphore and waits until it get notified by `onWritable()`. So when there is a failure the BackPressureObservable listener should be removed in order to release the semaphore through `onWritable()`.
> Remove backPressureObservable listener after failure

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/HttpWsConnectorFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
If we have an HttpClientConnector creator method that accepts the client `BootstrapConfiguration` as an argument, it will be beneficial when we have to create multiple client connectors for the same client, as it avoids initializing the `BootstrapConfiguration` each time.
This PR introduces a new HttpClientConnector creator method to `HttpWsConnectorFactory` interface.
> Introduce a new HttpClientConnector creator method to HttpWsConnectorFactory interface

- pom.xml
Update to the following versions 
- netty version to 4.1.73.Final
- netty-tcnative-boringssl-static to 2.0.48.Final
> Update netty transport version

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/certificatevalidation/Constants.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/certificatevalidation/ocsp/OCSPVerifier.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/certificatevalidation/pathvalidation/CertificatePathValidator.java
This PR introduces a new System property `security.jce.provider` which can be used to change the Crypto Provider from its default `BouncyCastleProvider` for  `BouncyCastleFipsProvider`.
Related to https://github.com/wso2/api-manager/issues/1219
To toggle the Crypto Provider to the `BouncyCastleFipsProvider` provider, provide the following system provider while starting up the server.
```sh
... -Dsecurity.jce.provider=BCFIPS ...
```
> Introduce system property to change crypto provider

- components/org.wso2.transport.http.netty/pom.xml
- features/org.wso2.transport.http.netty.feature/pom.xml
- pom.xml
Following dependencies have been upgraded
- guava -> 32.1.2-jre
- netty -> 4.1.97.Final
- snakeyaml -> 2.0
> Upgrading guava and netty versions

- pom.xml
Upgrade the netty dependency version to 4.1.104.Final, and Guava version to the 33.0.0-jre.
> Upgrade Netty and Guava versions

- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/HttpClientConnector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/HttpWsConnectorFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketClientConnector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/ssl/SSLConfig.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/HttpClientChannelInitializer.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClient.java
- components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketClientConnector.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/disablessl/SslDisabledClientTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/ssl/DisableSslTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/ssl/Http2ALPNwithCertsTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/ssl/Http2MutualSslTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/ssl/TestHttp2WithALPN.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/CipherSuitesTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/CipherSuiteswithCertsTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/HttpsInvalidServerCertificateTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/MutualSSLTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/MutualSSLwithCertsTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/OptionalMutualSSLTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/SSLProtocolsTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/SSLProtocolsWithCertsTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/ServerCloseConnectionDuringSslTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassthroughHttpsMessageProcessorListener.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/pkcs/PKCSTest.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/ssl/WebSocketSSLHandshakeFailureTestCase.java
- components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/ssl/WebSocketSSLHandshakeSuccessfulTestCase.java
Introduced new APIs to create HTTPS clients which can be created with SSL context initialisation
- Move the SSL context initialisation to client initialisation
> Initialise SSL context in the client initialisation
