wso2/transport-http

components/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/HTTPServerChannelInitializer.java
components/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/listener/HTTPTraceLoggingHandler.java
components/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/sender/HTTPClientInitializer.java
components/org.wso2.carbon.transport.http.netty/src/main/java/org/wso2/carbon/transport/http/netty/sender/RedirectChannelInitializer.java

>This PR  changes the log level for HTTP trace logs from DEBUG to TRACE.
> [ballerina/pull/4065](https://github.com/ballerinalang/ballerina/pull/4065)

Change HTTP trace log level from DEBUG -> TRACE

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java

> Flush the chunks immediately. 
> Not to delay the response.
> use writeAndFlush
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Change write to writeAndFlush

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/SenderConfiguration.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpClientConnectorImpl.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/CustomHttpContentCompressor.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/HTTP2SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HTTPClientInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/chunkdisable/ChunkHeaderClientTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/redirect/HTTPClientRedirectTestCase.java

> Make HTTP version configurable in sender configuration.
> Client connector configurability
> Add sender configuration HTTP version variable. Set it to the netty response message.

Add client connector option - HTTP version 

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/BlockingEntityCollector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java

> Fix any possible concurrency issue that could occur from the transport code.
> Making the code stable. 
> Using java locks and conditions. 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> Describe migration steps and platforms on which migration has been tested
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

Fix possible concurrency issue

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/ServerConnectorBootstrap.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPConnectorUtil.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/connectionpool/ConnectionPoolMainTestCase.java

> Removing usage of carbon-messaging constants from http implementation. At the same time refactored the code to make it more readable and maintainable. 
> Making the code more readable. 
> Applying proper abstraction.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Covered by existing testcases
- N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Refactor the code

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java

Allow multiple headers with same header key.

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/UriAndHeaderLengthValidator.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/urilengthvalidation/Status414And413ResponseTest.java

> Bug fix.
> Improve stability. 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Improved.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Fix the bug in 413, 414 response handler

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/websocket/WebSocketUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketSourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketTargetHandler.java

> Resolve https://github.com/ballerina-lang/ballerina/issues/3832
> Avoid memory leaks in the future.
> The pooled resources are released to avoid memory leaks. The binary data is cloned before releasing.
> Fix memory leak in WebSocket implementation
>N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
N/A
> N/A
> N/A
> N/A
> java 8, Ubuntu 17.10
> N/A.

Fix memory leak in WebSocket and refactor code

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HTTPClientInitializer.java

> Support decompression in client connector.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> yes
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Add decompressor handler to client-pipeline

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/certificatevalidation/RevocationVerificationManager.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/certificatevalidation/cache/CacheManager.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/certificatevalidation/crl/CRLVerifier.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/certificatevalidation/ocsp/OCSPVerifier.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/certificatevalidation/pathvalidation/PathChecker.java

Refactor java doc comments.

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java

> Provide full carbon message if a server connector requires.
> Notify server connector with the payload.
> Keep status of payload requirement in the carbon message.
> Once the full payload is accumulated, notify server connector.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
> N/A
- Ran FindSecurityBugs plugin and verified report? N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Add flag to notify server connector with payload

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/ListenerConfiguration.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/SenderConfiguration.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpWsConnectorFactoryImpl.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HTTPServerChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/ServerConnectorBootstrap.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HTTPClientInitializer.java

Add deault cache size as 50 and cache validity period as 15.
Change validateCertificateEnabled into validateCertEnabled.

Add default cache values.

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketClient.java

This PR refactor WebSocket client code and change some naming conventions to be more specific.

[WebSocket] Refactor WebSocket Client

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java

> Each time we create a client connector we create a separate thread pool. This PR avoids that and create one thread pool for all the clients. 
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Use a separate thread pool for clients

---

.travis.yml

With this .travis.yml configuration, the transport-http repository can be integrated with Travis CI.

Add .travis.yml configuration

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketSourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/compression/ServerRespCompressionTestCase.java

>
Print warn message only for unknown encoding values
> Print warn message only for unknown encoding values
> Put another if condition for encoding value check.

Print warn message only for unknown encoding values

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketInitMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WsClientConnectorConfig.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketClientConnector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketInitMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketServerHandshakeHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketSourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketClient.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketTargetHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWebSocketProtocolSwitchMultiThreadTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWebSocketProtocolSwitchTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWsProtocolSwitchWebSocketMulthreadListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketPassthroughServerConnectorListener.java
components/org.wso2.transport.http.netty/src/test/resources/testng.xml

> WebSocket handshake wasn't working when called in a multithreaded environment. This fixes it.

Fix issues in webSocket handshake

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HttpServerChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SslHandshakeCompletionHandlerForServer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/TLSHandshakeCompletionHandlerForServer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/CertificateValidationHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HttpClientChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/SslHandshakeCompletionHandlerForClient.java

Stop adding handlers to pipeline if TLS handshake fails.
If TLS handshake fails, rest of the handlers will not be added to the server channel pipeline.
They will be added only if the handshake becomes successful, otherwise channel will be closed.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in …

Stop adding handlers to pipeline if handshake fails

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SslHandshakeCompletionHandlerForServer.java

Fix PTT ssl issue

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassThroughHttpsTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/passthrough/PassthroughHttpsMessageProcessorListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestUtil.java
components/org.wso2.transport.http.netty/src/test/resources/testng.xml

A test case to check https pass-through scenario.
> Link to the PR for changes to the training content in …

Add a test case for https passthrough scenario

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/ssl/SSLHandlerFactory.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HttpServerChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SslHandshakeCompletionHandlerForServer.java

Fix the issue : https://github.com/ballerina-lang/ballerina/issues/5334

Fix the issue : Http2 enabled server fails to send response to http2 not supported clients

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HttpClientChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/redirect/HttpClientRedirectTestCase.java

Add proper SSL engine for redirect handler

Add proper SSL engine for redirect handler

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http1point0test/ChunkAlwaysHttpOnePointZeroServerTestCase.java

Improve chunk handling in listener side

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/redirect/HttpClientRedirectTestCase.java

Fix query param being dropped from location url

Fix query param being dropped from location url

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/DefaultObservable.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/Listener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/Observable.java

To throttle inbound read operation.

Trigger manual read

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java

Sync data stream write and io exception set

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketFrameType.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketConnection.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/websocket/WebSocketUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketSourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketTargetHandler.java

This resolves https://github.com/wso2/transport-http/issues/135

[WebSocket] Add support for Continuation WebSocket Frames

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/Http2OutboundRespListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/Http2SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/Http2SourceHandlerBuilder.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HttpAccessLoggingHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/HttpServerChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java

Access logs are not getting printed for HTTP/2 messages. Need to fix that.
Fix HTTP/2 access logs

Fix HTTP/2 access logs

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/ServerConnectorFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/Listener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/Observable.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/RedirectUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/pool/ConnectionManager.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketClient.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/redirect/HttpClientRedirectTestCase.java
components/org.wso2.transport.http.netty/src/test/resources/log4j.properties

Make sure that SH and TH runs on the same EventLoop

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/ClientOutboundHandler.java

Improve ClientOutboundHandler to mark the completion of writing.
> Link to the PR for changes to the training content in …

Improve ClientOutboundHandler to mark the completion of writing

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java

> Allow entity body for DELETE out request

Allow entity body for DELETE outbound request

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketInitMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/internal/websocket/DefaultWebSocketSession.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketServerHandshakeHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketSourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketClient.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketTargetHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/websocket/WebSocketClientHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/websocket/WebSocketTestClient.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketClientTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketMessagePropertiesTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/WebSocketServerTestCase.java

This PR addresses the transport related part of https://github.com/ballerina-platform/ballerina-lang/issues/7893

Fix WebSocket Connection Closure Issue

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/RequestSizeValidationConfig.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/MaxEntityBodyValidator.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/BlockingEntityCollector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/EntityCollector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/BadEchoServerInitializer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/EchoServerInitializer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/HttpToWsProtocolSwitchHttpListener.java

This will fix the overflow error

Use long type to hold content length

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2ClientChannel.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/TimeoutHandler.java

[HTTP2] Fix possible OOM situation with burst of request timeouts

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/ClientInboundHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2ClientChannel.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2ConnectionManager.java

Receiving a GOAWAY frame means a fatal incident. If it happens we shouldn't reuse a channel again.
This PR address that.
> Link …

[HTTP2] Handle GOAWAY frame at Http Client side

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java

> Add listener to notify the failure of response header write operation

Notify response header write failures

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java

> Notify failure of outbound request headers

Notify failure of outbound request headers

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java

>  Reset inbound request's state once the out response is notified. 
> Make inbound request reusable

Reset inbound request's state once the out response is notified

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java

Reverts wso2/transport-http#159

Revert "Reset inbound request's state once the out response is notified"

---

components/org.wso2.transport.http.netty/pom.xml
pom.xml

> Add unirest test framework dependencies

Add unirest test framework dependencies

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/MessageFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java

> Move channel reset to the initial stage of write operation
> Remove message future automatically in setMessageListener

Move channel reset and remove message future after the LastHttpContent

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HttpClientChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/pool/PoolableTargetChannelFactory.java

Fix for the issue - https://github.com/ballerina-platform/ballerina-lang/issues/8563
> Link to the PR for changes to the training …

Fix for not applying of proxy rules through netty proxy handler

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/hostnameverfication/HostnameVerificationTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/TestHttp2WithALPN.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/HTTPSClientTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/MutualSSLTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/SSLProtocolsTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/ocspstapling/OCSPStaplingTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/pkcs/PKCSTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/proxyserver/ProxyServerTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/redirect/HttpClientRedirectTestCase.java

Removed the usage of netty-transports.yml from test classes.

Remove the usage of netty-transports.yml

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/BlockingEntityCollector.java

Fix content adding incorrect order

Fix HTTP Content order issue

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/ssl/SSLHandlerFactory.java

Fix : https://github.com/ballerina-platform/ballerina-lang/issues/8713

Change "ssl.KeyManagerFactory.algorithm"

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/hostnameverfication/HostnameVerificationTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/TestHttp2WithALPN.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/CipherSuitesTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/MutualSSLTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/SSLProtocolsTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/ocspstapling/OCSPStaplingTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/pkcs/PKCSTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/proxyserver/HttpProxyServerTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/proxyserver/HttpsProxyServerTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/proxyserver/ProxyServerUtil.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/redirect/HttpClientRedirectTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestUtil.java

Reduce the number of ports used in test cases

Reduce the number of ports used in test cases

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/pool/PoolableTargetChannelFactory.java

Fix the issue of not connecting to an https endpoint through a squid proxy server.

Fix a proxy server issue

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/ServerConnectorFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketConnectorListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpWsServerConnectorFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketSourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketTargetHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/websocket/WebSocketTestClient.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/websocket/WebSocketRemoteServerFrameHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketClientFunctionalityTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketTestClientConnectorListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/passthrough/WebSocketPassThroughClientConnectorListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/passthrough/WebSocketPassThroughServerConnectorListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketServerFunctionalityTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketServerHandshakeFunctionalityListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketTestServerConnectorListener.java

> Fix on error notification issues in transport. 
> This PR fixes https://github.com/wso2/transport-http/issues/187

[WebSocket] Fix on error notification issue

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/Http2OutboundRespListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/Http2SourceConnectionHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/Http2SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/BlockingEntityCollector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/channel/TargetChannel.java

Fix https://github.com/ballerina-platform/ballerina-lang/issues/8831
> Link to the PR for changes to the training content in …

Fix OutOfDirectMemoryError when invoking HTTP2 ballerina service

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketClientHandshakeHandler.java

This PR fixes existing insecure SSL handling issue

Fix existing insecure SSL connection handler issue

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/proxyserver/HttpsProxyServerTestCase.java

Fix the issue : https://github.com/ballerina-platform/ballerina-lang/issues/8850

Fix the issue : https://github.com/ballerina-platform/ballerina-lang/issues/8850

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/MessageFuture.java

Fix message content lose when writing outbound message

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceErrorHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java

Fix https://github.com/ballerina-platform/ballerina-lang/issues/9239
> Link to the PR for changes to the training content in …

Fix NPE of SourceErrorHandler

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/Http2ToHttpFallbackHandler.java

Fix https://github.com/ballerina-platform/ballerina-lang/issues/9044
Error scenario and the root cause is described in the issue thread.

Fix NPE due to HTTP2 to HTTP1 fallback handler

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HTTPCarbonMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/MessageFuture.java

> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/9100

Fix http2 client payload disordering issue

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/OutboundMsgHolder.java

Remove remaining unused redirect code snippets

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/exception/ConfigurationException.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/TargetHandler.java

To update https://github.com/wso2/transport-http/pull/227

Refactor Sourcehandler/TargetHandler code

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketClientConnectorConfig.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketConnection.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketConnectorException.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketInitMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultServerHandshakeFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketConnection.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketConnectorFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/WebSocketInboundFrameHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketInitMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketTextMessage.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/WebSocketServerHandshakeHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketClientHandshakeHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/websocket/WebSocketTestClient.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/websocket/WebSocketRemoteServerFrameHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/websocket/WebSocketServerCustomHeadersHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketClientFunctionalityTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketClientHandshakeFunctionalityTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/client/WebSocketTestClientConnectorListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketServerHandshakeFunctionalityListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketServerHandshakeFunctionalityTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/ssl/WebSocketSSLHandshakeFailureTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/ssl/WebSocketSSLHandshakeSuccessfulTestCase.java

> Increase the test coverage
> Increase the test coverage of WebSocket above 80%
> Remove redundant code which is not tested and add missing test cases.

Add missing test cases and remove redundant code

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/certificatevalidation/ocsp/OCSPVerifier.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/common/ssl/SSLConfig.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/ListenerConfiguration.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/config/SslConfiguration.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpWsConnectorFactory.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/HttpClientChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/websocket/WebSocketClient.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/CipherSuitesTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/MutualSSLTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/SSLProtocolsTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/pkcs/PKCSTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/HttpsServer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/ssl/WebSocketSSLHandshakeFailureTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/ssl/WebSocketSSLHandshakeSuccessfulTestCase.java

Fix the issue: https://github.com/wso2/transport-http/issues/211

Refactor ssl related configurations to improve re-usability

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/certificatevalidation/RevocationVerificationTest.java

Remove the throwable check in ocspPathValidation test

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/9694

Remove ioException from data streamer

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/Http2SourceConnectionHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/Http2SourceConnectionHandlerBuilder.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/Http2SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/Http2ToHttpFallbackHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/http2/Http2WithPriorKnowledgeHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/Http2PushPromise.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/Http2Reset.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/ClientFrameListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2ClientChannel.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2ConnectionManager.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2DataEventListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/Http2TargetHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/OutboundMsgHolder.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/sender/http2/TimeoutHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ClientConnectorBasicTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ClientTimeoutTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ServerConnectorBasicTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ServerPushTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2WithPriorKnowledgeTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/listeners/Http2RedirectListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/listeners/Http2ServerConnectorListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/http2/MessageGenerator.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/client/http2/MessageSender.java

- Refactor and reformat HTTP/2 related classes and test cases
- Improve code readability
> Please note that this does not have any functional changes

Refactor HTTP/2 code

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/states/listener/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/states/listener/ResponseCompleted.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/states/sender/EntityBodyReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/listener/states/sender/ReceivingEntityBody.java

> Fixes ballerina-platform/ballerina-lang#10274

Handle connection closure for incomplete request when response is received

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java

Introduce a method to remove inbound content listener

---

pom.xml

Upgrade bouncy-castle version

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/ConnectionAvailabilityFuture.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/ClientConnectorUnknownHostTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestUtil.java

Add proper error message when the host cannot be resolved

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/ConnectionAvailabilityFuture.java

Remove remote address from unknown host error message

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketClientConnectorConfig.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/WebSocketServerHandshakeHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClient.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/websocket/WebSocketRemoteServerInitializer.java

> The maxFrameSize config is required to let the user have more control.

Add config for maxFrameSize

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/Http2MessageStateContext.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/TimeoutHandler.java

- Fix PR reviews of java docs and log messages.

Fix for PR reviews

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/unitfunction/CommonUtilTestCase.java

Rename non-entity-body property name

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/OptionalMutualSSLTest.java

Fix a build failure in older java versions

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/SslHandshakeCompletionHandlerForServer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/HttpClientChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/SslHandshakeCompletionHandlerForClient.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClient.java

Fix the issue: https://github.com/ballerina-platform/ballerina-lang/issues/13255

Verify certificate expiry date

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/StateUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/TargetChannel.java

> $Title
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/10329

Address NoSuchElementException when adding idle state handler

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/TargetChannel.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/pool/ConnectionManager.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/pool/PoolableTargetChannelFactoryPerSrcHndlr.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/connectionpool/ConnectionPoolProxyTestCase.java

Add Target connection pool per each client

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/pool/ConnectionManager.java

Refactor connection manager code

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/pool/PoolableTargetChannelFactory.java

$subject
Please note that this does not do any functional changes

Refactor pool implementation

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingEntityBody.java

> Sets the flag which indicates the lastHttpContent arrival for HTTP2 requests and notify FullHttpMessageFuture if available

Notify last content arrival in HTTP2

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/StateUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/DefaultFullHttpMessageFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/FullHttpMessageListener.java

> $Title
> Add HttpCarbonMessage as parameter in FullHttpMessageListener onComplete method

Notify FullMessageFuture when inboundMsg is incomplete

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/Http2StateUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/http2/Http2SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ReceivingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/TargetChannel.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/pool/ConnectionManager.java

> Fix https://github.com/ballerina-platform/ballerina-lang/issues/13704

Fix HTTP/2 error rate that gets occurred under high load

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/http2/Http2SourceConnectionHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/certificatevalidation/Utils.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/TestHttp2WithALPN.java
pom.xml

Upgrade netty version from 4.1.19.Final to 4.1.34.Final.
Fix the issue: https://github.com/ballerina-platform/ballerina-lang/issues/13912

Upgrade netty version

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/H2ConnectionPoolWithPriorKnowledge.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/H2ChannelIdHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/H2ChannelIdHandlerBuilder.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/Http2EchoServerInitializer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/Http2SendChannelIDInitializer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/Http2ServerInitializer.java
components/org.wso2.transport.http.netty/src/test/resources/testng.xml

Add support for prior knowledge in transport test backend and enable relevant tests

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java

Synchronize the HTTP content release

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/SslHandshakeCompletionHandlerForServer.java

Fix https://github.com/wso2/transport-http/issues/314

Fix Netty SSL exception on server startup

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java

> Disable content release in the data stream close()
> Remove temporarily added logs

Disable content release in the data stream close function

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java

Reverts wso2/transport-http#323

Remove logs added for mem leak issue

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/ServerConnectorBootstrap.java

> Fix https://github.com/wso2/transport-http/issues/321

Fix issue in logging HTTP host

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/http2/Http2SourceHandler.java

Fix failing http/2 upgrade scenario

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java

Add a string constant for HTTP/2 version

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpResponseFuture.java

Fix thread hanging issue in HTTP/2 submit method when the remote server is down

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/Http2StateUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/ClientFrameListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2TargetHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/TimeoutHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/EntityBodyReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/RequestCompleted.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SenderState.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SendingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SendingHeaders.java

Add timeout implementation for HTTP/2 push response

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/TargetHandler.java

Fix the issue: https://github.com/ballerina-platform/ballerina-lang/issues/14647

Avoid sending the 100-continue response to the Ballerina side.

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/ConnectionAvailabilityFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/SslHandshakeCompletionHandlerForClient.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/hostnameverfication/HostnameVerificationTest.java

Fix the issue: https://github.com/ballerina-platform/ballerina-lang/issues/16042

Provide the root cause of the SSL error as the client connector exception

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/WebSocketMessageQueueHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClient.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClientHandshakeHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketConnection.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/WebSocketInboundFrameHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketHandshaker.java

Rename class MessageQueueHandler to WebSocketMessageQueueHandler

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/Http2StateUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ListenerState.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/TargetHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2ClientTimeoutHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/EntityBodyReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/RequestCompleted.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SenderState.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SendingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SendingHeaders.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/H2ConnectionPoolWithPriorKnowledge.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/H2ConnectionPoolWithUpgrade.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ServerConnectorBasicTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/clienttimeout/TimeoutAfterRequestWrite.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/clienttimeout/TimeoutDuringRequestWrite.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/clienttimeout/TimeoutDuringResponseReceive.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/connectionpool/H2ConnectionPoolWithALPN.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/connectionpool/H2ConnectionPoolWithPriorKnowledge.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/connectionpool/H2ConnectionPoolWithUpgrade.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/listeners/Http2ServerWaitDuringDataWrite.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/Http2Util.java
components/org.wso2.transport.http.netty/src/test/resources/testng.xml

Handle HTTP/2 client timeout based on the state the stream is in

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/WebSocketInboundFrameHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketHandshaker.java

> This PR includes simple improvements like releasing certain resources properly and removing unnecessary code blocks.
> Fix minor bugs
> Fix bugs noticed during tests.
> N/A
> N/A
> N/A
> N/A
> N/A
>N/A
- Unit tests 
> N/A
> N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no
> Provide high-level details about the samples related to this feature
> List any other related PRs
> Describe migration steps and platforms on which migration has been tested
> List all JDK versions, operating systems, databases, and browser/versions on which this …

Release resources properly

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/SenderReqRespStateManager.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/EntityBodyReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/RequestCompleted.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SenderState.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/Sending100Continue.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SendingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SendingHeaders.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/expect100continue/ClientContinue100ChunkingTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/expect100continue/ClientContinue100ClosureTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/expect100continue/ClientContinue100ContentLengthTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/expect100continue/ClientContinue100ResponseTimeoutTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/expect100continue/ClientContinue100TimeoutTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/Dumb100ContinueServerInitializer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/EchoServerInitializer.java
components/org.wso2.transport.http.netty/src/test/resources/testng.xml
pom.xml

Expect:Continue implementation for Client

---

components/org.wso2.transport.http.netty.statistics/pom.xml
components/org.wso2.transport.http.netty/pom.xml
features/org.wso2.transport.http.netty.feature/pom.xml
features/org.wso2.transport.http.netty.statistics.feature/pom.xml

> $Subject
> Sub-module version update can be done using following command after changing it to the required version in the parent pom 
`mvn -N versions:update-child-modules`

Update sub-module versions

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/certificatevalidation/OCSPStaplingTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/certificatevalidation/RevocationVerificationTest.java

Enable ocsp test cases

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/Expect100ContinueHeaderReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ReceivingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/Response100ContinueSent.java

Send 100-continue response with HTTP/2 server when expect header is present

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/server/WebSocketServerHandshakeFunctionalityTestCase.java

> Disable intermittently failing test

Disable intermittently failing test

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClient.java

if we use sync() , 
- waits for this future until it is done, and rethrows the cause of the failure if this future failed.
- executes an infinite loop, doesn't return from a call to request some resource. 
So I use addlistener() insteadof sync(). 
> Link(s) to product documentation …

Remove the chance to happen deadlock in the webSocket

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpMessageDataStreamer.java

> $Subject
> Related to https://github.com/wso2/transport-http/pull/312

Release remnant HTTP Content at InputStream close()

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2TargetHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/Http2ClientConnectorBasicTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/connectionpool/H2ConnectionPoolWithALPN.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/connectionpool/H2ConnectionPoolWithPriorKnowledge.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/connectionpool/H2ConnectionPoolWithUpgrade.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/expect100continue/Abnormal100ContinueTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/Http2Util.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/HttpsServer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/http2/Http2EchoServerInitializer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/http2/Http2ServerInitializer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/http2/channelidsender/H2ChannelIdHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/http2/channelidsender/H2ChannelIdHandlerBuilder.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/http2/channelidsender/Http2SendChannelIDInitializer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/http2/expect100continue/Abnormal100ContinueHandler.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/http2/expect100continue/Abnormal100ContinueHandlerBuilder.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/server/initializers/http2/expect100continue/Abnormal100ContinueServerInitializer.java
components/org.wso2.transport.http.netty/src/test/resources/testng.xml

Handle unexpected 100 continue responses in HTTP/2 client

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/ConnectionAvailabilityFuture.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/HttpsInvalidServerCertificateTest.java
components/org.wso2.transport.http.netty/src/test/resources/testng.xml

Fix the issue: https://github.com/ballerina-platform/ballerina-lang/issues/17837

Provide a meaningful error for invalid server certificate

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/EntityBodyReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/Expect100ContinueHeaderReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/Expect100ContinueHeaderReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java

Remove the default status code value

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/SenderReqRespStateManager.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/pool/PoolableTargetChannelFactory.java

Fix connection closure

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/ReceivingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingHeaders.java

Move unnecessary logs to debug log level

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/SenderReqRespStateManager.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/TargetHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/EntityBodyReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/RequestCompleted.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SenderState.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/Sending100Continue.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SendingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SendingHeaders.java

Fix issue in handleAbruptChannelClosure in SendingEntityBody state

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/DefaultBackPressureListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java

Fix thread hanging issue

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/StateUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/ReceivingHeaders.java

Change state after timeout response

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/http2/Http2ExceptionHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/HttpExceptionHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/HttpServerChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/http2/Http2SourceConnectionHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/ConnectionAvailabilityFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/HttpClientChannelInitializer.java

Fix the issue: https://github.com/ballerina-platform/ballerina-lang/issues/18452

Handle exceptions thrown during TLS handshake

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/SendingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/TargetHandler.java

Fix the thread hanging issue in Listener side

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/SenderReqRespStateManager.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/TargetHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/EntityBodyReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/RequestCompleted.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SenderState.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/Sending100Continue.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SendingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/SendingHeaders.java

Fix the issue in idle timeout while sending entity body

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/ConnectionAvailabilityFuture.java

Add a null check before getting the channelFuture.cause().getMessage()

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/ConnectionAvailabilityFuture.java

Fix null pointer in SSL handshake

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingEntityBody.java

> $Subject. 
> Occurred while testing idle timeout connection closure during client inbound entity body read
> Link to the PR for …

Fix NoSuchElement exception for idle state handler

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/ConnectionAvailabilityFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/SslHandshakeCompletionHandlerForClient.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/HttpsInvalidServerCertificateTest.java

Remove string comparison for unknown host exception

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/BackPressureHandler.java

Remove instance of check for backpressure listener

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java

Fix OOM issue

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/websocket/WebSocketClientConnectorConfig.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/HttpServerChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/WebSocketServerHandshakeHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClient.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/websocket/WebSocketClientHandshakeHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/DefaultWebSocketConnection.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/websocket/message/DefaultWebSocketHandshaker.java

Improve WebSocket code

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/Http2OutboundRespListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/http2/Http2SourceConnectionHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/http2/Http2SourceHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/EntityBodyReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/Expect100ContinueHeaderReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ListenerState.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ReceivingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/Response100ContinueSent.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ResponseCompleted.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/SendingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/SendingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2ClientChannel.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SendingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/ServerRemoteFlowControlListener.java

$subject
Fix >> https://github.com/ballerina-platform/ballerina-lang/issues/19091

Fix HTTP/2 OOM that gets occurred due to premature connection close when transferring a large amount of data  

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/Http2StateUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/EntityBodyReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/ReceivingEntityBody.java

Fix https://github.com/ballerina-platform/ballerina-lang/issues/19047

Fix erroneously sending end stream flag with 100-continue response

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/message/HttpCarbonMessage.java

> $subject. 
This was added in a hurry and as it turns out we don't need this code anymore.

Remove unwanted code

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2ClientTimeoutHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/http2/Http2TargetHandler.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/EntityBodyReceived.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/RequestCompleted.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SenderState.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SendingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/SendingHeaders.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/WaitingFor100Continue.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/expect100continue/ClientContinue100ChunkingTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/expect100continue/ClientContinue100TimeoutTestcase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/expect100continue/ClientContinueResponseTimeout.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/expect100continue/Continue100Util.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/expect100continue/Expect100ContinueClientTestCase.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestUtil.java
components/org.wso2.transport.http.netty/src/test/resources/testng.xml

Implement 100-continue support for HTTP2

---

components/org.wso2.transport.http.netty/pom.xml

Update maven sure plugin version

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java

> Add HTTP header Validation
> HTTP Response Splitting Attack

Add HTTP header Validation

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/SendingEntityBody.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/states/http2/SendingEntityBody.java

> When an empty payload is sent, the EmptylastHttpContent is set as the last content. Since EmptylastHttpContent is a read-only content, trailers cannot be added. Hence new DefaultHttplastContent is replaced for EmptylastHttpContent.
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/21230
> Brief description of the new feature or bug fix as it will …

Replace EmptyHttpContent with defaultHttpContent when setting trailers

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/Http2StateUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/HttpServerChannelInitializer.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/SslHandshakeCompletionHandlerForServer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/ssl/Http2ALPNwithCertsTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/ssl/Http2MutualSslTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/ssl/TestHttp2WithALPN.java
components/org.wso2.transport.http.netty/src/test/resources/testng.xml

$subject
Fix the issue: https://github.com/ballerina-platform/ballerina-lang/issues/21381

Pass the mutual ssl handshake result to ballerina

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/Http2StateUtil.java

Pass the end user certificate to the ballerina side

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/StateUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/ReceivingEntityBody.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/trailer/ClientReadTrailerHeaderTestCase.java

> $subject and fix test intermittent test failure of https://wso2.org/jenkins/view/platform/job/platform-builds/job/transport-http/724/

Fix order of trailer execution and test failure

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/states/Http2StateUtil.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/http2/Http2SourceHandler.java

> $Title
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/22821

Populate remote-address to the HCM in HTTP2 flow

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/Http2OutboundRespListener.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/compression/ResponseBodyCompressionTestCase.java

Include the not supporting encoding schemes to the debug log.

Update the debug log in Http2 compression

---

pom.xml

Upgrade Netty version 

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/common/Util.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/HttpClientChannelInitializer.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/ssl/DisableSslTest.java

This is to add support for disabling SSL certificate validation for HTTP2 clients.

Add disable SSL support for HTTP2

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/http2/ssl/DisableSslTest.java

Add a comment and fix the logger

---

pom.xml

> Update Netty-tcnative to 2.0.31.Final which have aarch64 support

Update Netty-tcnative to 2.0.31.Final

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/HttpClientChannelInitializer.java

> If HTTP 2 client fallback in the absence of compatible backend, the request/response should be treated as per the HTTP 1.1 configs. Hence adding response size threshold and validation handler to fallback path

Add client fallback size validation

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/Constants.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/states/http2/ReceivingHeaders.java

> Duplicate of https://github.com/ballerina-platform/module-ballerina-http/pull/104 to fix https://github.com/ballerina-platform/ballerina-standard-library/issues/327

Fix HTTP2 client hanging issue

---

.github/workflows/pull-request.yml

Add github action for PR builds

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/HttpResponseFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpResponseFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/TargetChannel.java

Refactored the code and handled the HTTP path backPressureObservable

Refactor backPressureObservable listener removal

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpResponseFuture.java

Remove unused imports

---

pom.xml

Update netty transport version

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/listener/http2/Http2SourceConnectionHandlerBuilder.java

Fix CompressorHttp2ConnectionEncoder constructor change

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/certificatevalidation/Utils.java

Temporarily remove service cipher parameters

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/certificatevalidation/Utils.java

Undo service cipher parameters removal and add server protocol params

---

pom.xml

Downgrade netty-tcnative-boringssl-static version to resolve unit test failures.
> Link to the PR for changes to the training …

Downgrade netty-tcnative-boringssl-static version

---

pom.xml

$subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Upgrade bouncycastle version

---

pom.xml

Update Netty version to 4.1.77.Final

---

pom.xml

Update snakeyaml version to 1.31.0

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/certificatevalidation/OCSPStaplingTest.java

> $subject
> Related https://github.com/ballerina-platform/ballerina-standard-library/issues/317#issuecomment-925515166

Disable testretrievingResponseFromWeb due to intermittent failure

---

pom.xml

$subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

Update snakeyaml version to 1.32.0

---

pom.xml

Update third-party dependencies

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/HttpResponseFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpClientConnector.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/DefaultHttpResponseFuture.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/Http2OutboundRespListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/HttpOutboundRespListener.java
components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contractimpl/sender/channel/TargetChannel.java

Fix BackPressureObservable issue for outbound response path

---

pom.xml

Upgrades snakeyaml version
Related git issue : https://github.com/wso2/api-manager/issues/1222
> Link to the PR for changes to …

Upgrade sankeyaml version

---

components/org.wso2.transport.http.netty/pom.xml
features/org.wso2.transport.http.netty.feature/pom.xml
pom.xml

Add missing dependencies for netty update

---

features/org.wso2.transport.http.netty.feature/pom.xml

Fix build failure

---

pom.xml

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4608
> Link to the PR for changes to …

Update vulnerable netty version

---

components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/SSLProtocolsTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/https/SSLProtocolsWithCertsTest.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/websocket/ssl/WebSocketSSLHandshakeFailureTestCase.java

This is to fix test failures in - `SSLProtocolsTest`, `SSLProtocolsWithCertsTest`, `WebSocketSSLHandshakeFailureTestCase`.
These are already updated in the swan lake transport and hence doing the same changes to this as well.
Refer - https://github.com/ballerina-platform/module-ballerina-http/pull/327/commits/ac55ebe903b39cf92fec6f7e264e02a5c3c8d420
> Brief description of …

Update test cases to fix ssl failures

---

components/org.wso2.transport.http.netty/src/main/java/org/wso2/transport/http/netty/contract/config/ConfigurationBuilder.java
components/org.wso2.transport.http.netty/src/test/java/org/wso2/transport/http/netty/util/TestUtil.java
pom.xml

Fix the build after snakeyaml upgrade to 2.0

---

pom.xml

Downgrade org.wso2 version to `5.0`

---

pom.xml

Downgrade org.wso2 version to 5

---

pom.xml

Include maven repositories

---

pom.xml

Bump snakeyaml from v2.0 to v2.2

Bump snakeyaml version

---

pom.xml

Update Netty version to the latest
